// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfAcceptContext struct {
	_                  structs.HostLayout
	ListenerFd         uint32
	ListenerGeneration uint32
	SockaddrAddr       uint64
}

type bpfReadContext struct {
	_          structs.HostLayout
	Fd         uint32
	Generation uint32
	Iovcnt     uint32
	IsIov      uint8
	Pad0       [3]uint8
	BufAddr    uint64
	BufLen     uint32
	Pad1       uint32
	IovAddr    uint64
}

type bpfSocketKey struct {
	_          structs.HostLayout
	Pid        uint32
	Fd         uint32
	Generation uint32
}

type bpfSocketTuple struct {
	_          structs.HostLayout
	Family     uint16
	LocalPort  uint16
	RemotePort uint16
	Role       uint8
	Flags      uint8
}

type bpfSslArgs struct {
	_      structs.HostLayout
	Buf    uint64
	LenOut uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	ProbeEntrySSL_read    *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_read"`
	ProbeEntrySSL_readEx  *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_read_ex"`
	ProbeEntrySSL_write   *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_write"`
	ProbeEntrySSL_writeEx *ebpf.ProgramSpec `ebpf:"probe_entry_SSL_write_ex"`
	ProbeRetSSL_read      *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_read"`
	ProbeRetSSL_readEx    *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_read_ex"`
	ProbeRetSSL_write     *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_write"`
	ProbeRetSSL_writeEx   *ebpf.ProgramSpec `ebpf:"probe_ret_SSL_write_ex"`
	TraceSysEnterAccept   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_accept"`
	TraceSysEnterAccept4  *ebpf.ProgramSpec `ebpf:"trace_sys_enter_accept4"`
	TraceSysEnterBind     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_bind"`
	TraceSysEnterClose    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_close"`
	TraceSysEnterConnect  *ebpf.ProgramSpec `ebpf:"trace_sys_enter_connect"`
	TraceSysEnterRead     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_read"`
	TraceSysEnterReadv    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_readv"`
	TraceSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"trace_sys_enter_recvfrom"`
	TraceSysEnterRecvmsg  *ebpf.ProgramSpec `ebpf:"trace_sys_enter_recvmsg"`
	TraceSysEnterSendmsg  *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendmsg"`
	TraceSysEnterSendto   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendto"`
	TraceSysEnterWrite    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_write"`
	TraceSysEnterWritev   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_writev"`
	TraceSysExitAccept    *ebpf.ProgramSpec `ebpf:"trace_sys_exit_accept"`
	TraceSysExitAccept4   *ebpf.ProgramSpec `ebpf:"trace_sys_exit_accept4"`
	TraceSysExitRead      *ebpf.ProgramSpec `ebpf:"trace_sys_exit_read"`
	TraceSysExitReadv     *ebpf.ProgramSpec `ebpf:"trace_sys_exit_readv"`
	TraceSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"trace_sys_exit_recvfrom"`
	TraceSysExitRecvmsg   *ebpf.ProgramSpec `ebpf:"trace_sys_exit_recvmsg"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveAccepts   *ebpf.MapSpec `ebpf:"active_accepts"`
	ActiveReads     *ebpf.MapSpec `ebpf:"active_reads"`
	ActiveSslReads  *ebpf.MapSpec `ebpf:"active_ssl_reads"`
	ActiveSslWrites *ebpf.MapSpec `ebpf:"active_ssl_writes"`
	AllowedCgroups  *ebpf.MapSpec `ebpf:"allowed_cgroups"`
	CaptureConfig   *ebpf.MapSpec `ebpf:"capture_config"`
	DropMetrics     *ebpf.MapSpec `ebpf:"drop_metrics"`
	EventSeqnos     *ebpf.MapSpec `ebpf:"event_seqnos"`
	Events0         *ebpf.MapSpec `ebpf:"events_0"`
	Events1         *ebpf.MapSpec `ebpf:"events_1"`
	Events2         *ebpf.MapSpec `ebpf:"events_2"`
	Events3         *ebpf.MapSpec `ebpf:"events_3"`
	Events4         *ebpf.MapSpec `ebpf:"events_4"`
	Events5         *ebpf.MapSpec `ebpf:"events_5"`
	Events6         *ebpf.MapSpec `ebpf:"events_6"`
	Events7         *ebpf.MapSpec `ebpf:"events_7"`
	FdGenerations   *ebpf.MapSpec `ebpf:"fd_generations"`
	IgnoredPorts    *ebpf.MapSpec `ebpf:"ignored_ports"`
	SocketTuples    *ebpf.MapSpec `ebpf:"socket_tuples"`
	TargetPids      *ebpf.MapSpec `ebpf:"target_pids"`
	TargetPorts     *ebpf.MapSpec `ebpf:"target_ports"`
	ThreadLastFd    *ebpf.MapSpec `ebpf:"thread_last_fd"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveAccepts   *ebpf.Map `ebpf:"active_accepts"`
	ActiveReads     *ebpf.Map `ebpf:"active_reads"`
	ActiveSslReads  *ebpf.Map `ebpf:"active_ssl_reads"`
	ActiveSslWrites *ebpf.Map `ebpf:"active_ssl_writes"`
	AllowedCgroups  *ebpf.Map `ebpf:"allowed_cgroups"`
	CaptureConfig   *ebpf.Map `ebpf:"capture_config"`
	DropMetrics     *ebpf.Map `ebpf:"drop_metrics"`
	EventSeqnos     *ebpf.Map `ebpf:"event_seqnos"`
	Events0         *ebpf.Map `ebpf:"events_0"`
	Events1         *ebpf.Map `ebpf:"events_1"`
	Events2         *ebpf.Map `ebpf:"events_2"`
	Events3         *ebpf.Map `ebpf:"events_3"`
	Events4         *ebpf.Map `ebpf:"events_4"`
	Events5         *ebpf.Map `ebpf:"events_5"`
	Events6         *ebpf.Map `ebpf:"events_6"`
	Events7         *ebpf.Map `ebpf:"events_7"`
	FdGenerations   *ebpf.Map `ebpf:"fd_generations"`
	IgnoredPorts    *ebpf.Map `ebpf:"ignored_ports"`
	SocketTuples    *ebpf.Map `ebpf:"socket_tuples"`
	TargetPids      *ebpf.Map `ebpf:"target_pids"`
	TargetPorts     *ebpf.Map `ebpf:"target_ports"`
	ThreadLastFd    *ebpf.Map `ebpf:"thread_last_fd"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveAccepts,
		m.ActiveReads,
		m.ActiveSslReads,
		m.ActiveSslWrites,
		m.AllowedCgroups,
		m.CaptureConfig,
		m.DropMetrics,
		m.EventSeqnos,
		m.Events0,
		m.Events1,
		m.Events2,
		m.Events3,
		m.Events4,
		m.Events5,
		m.Events6,
		m.Events7,
		m.FdGenerations,
		m.IgnoredPorts,
		m.SocketTuples,
		m.TargetPids,
		m.TargetPorts,
		m.ThreadLastFd,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	ProbeEntrySSL_read    *ebpf.Program `ebpf:"probe_entry_SSL_read"`
	ProbeEntrySSL_readEx  *ebpf.Program `ebpf:"probe_entry_SSL_read_ex"`
	ProbeEntrySSL_write   *ebpf.Program `ebpf:"probe_entry_SSL_write"`
	ProbeEntrySSL_writeEx *ebpf.Program `ebpf:"probe_entry_SSL_write_ex"`
	ProbeRetSSL_read      *ebpf.Program `ebpf:"probe_ret_SSL_read"`
	ProbeRetSSL_readEx    *ebpf.Program `ebpf:"probe_ret_SSL_read_ex"`
	ProbeRetSSL_write     *ebpf.Program `ebpf:"probe_ret_SSL_write"`
	ProbeRetSSL_writeEx   *ebpf.Program `ebpf:"probe_ret_SSL_write_ex"`
	TraceSysEnterAccept   *ebpf.Program `ebpf:"trace_sys_enter_accept"`
	TraceSysEnterAccept4  *ebpf.Program `ebpf:"trace_sys_enter_accept4"`
	TraceSysEnterBind     *ebpf.Program `ebpf:"trace_sys_enter_bind"`
	TraceSysEnterClose    *ebpf.Program `ebpf:"trace_sys_enter_close"`
	TraceSysEnterConnect  *ebpf.Program `ebpf:"trace_sys_enter_connect"`
	TraceSysEnterRead     *ebpf.Program `ebpf:"trace_sys_enter_read"`
	TraceSysEnterReadv    *ebpf.Program `ebpf:"trace_sys_enter_readv"`
	TraceSysEnterRecvfrom *ebpf.Program `ebpf:"trace_sys_enter_recvfrom"`
	TraceSysEnterRecvmsg  *ebpf.Program `ebpf:"trace_sys_enter_recvmsg"`
	TraceSysEnterSendmsg  *ebpf.Program `ebpf:"trace_sys_enter_sendmsg"`
	TraceSysEnterSendto   *ebpf.Program `ebpf:"trace_sys_enter_sendto"`
	TraceSysEnterWrite    *ebpf.Program `ebpf:"trace_sys_enter_write"`
	TraceSysEnterWritev   *ebpf.Program `ebpf:"trace_sys_enter_writev"`
	TraceSysExitAccept    *ebpf.Program `ebpf:"trace_sys_exit_accept"`
	TraceSysExitAccept4   *ebpf.Program `ebpf:"trace_sys_exit_accept4"`
	TraceSysExitRead      *ebpf.Program `ebpf:"trace_sys_exit_read"`
	TraceSysExitReadv     *ebpf.Program `ebpf:"trace_sys_exit_readv"`
	TraceSysExitRecvfrom  *ebpf.Program `ebpf:"trace_sys_exit_recvfrom"`
	TraceSysExitRecvmsg   *ebpf.Program `ebpf:"trace_sys_exit_recvmsg"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.ProbeEntrySSL_read,
		p.ProbeEntrySSL_readEx,
		p.ProbeEntrySSL_write,
		p.ProbeEntrySSL_writeEx,
		p.ProbeRetSSL_read,
		p.ProbeRetSSL_readEx,
		p.ProbeRetSSL_write,
		p.ProbeRetSSL_writeEx,
		p.TraceSysEnterAccept,
		p.TraceSysEnterAccept4,
		p.TraceSysEnterBind,
		p.TraceSysEnterClose,
		p.TraceSysEnterConnect,
		p.TraceSysEnterRead,
		p.TraceSysEnterReadv,
		p.TraceSysEnterRecvfrom,
		p.TraceSysEnterRecvmsg,
		p.TraceSysEnterSendmsg,
		p.TraceSysEnterSendto,
		p.TraceSysEnterWrite,
		p.TraceSysEnterWritev,
		p.TraceSysExitAccept,
		p.TraceSysExitAccept4,
		p.TraceSysExitRead,
		p.TraceSysExitReadv,
		p.TraceSysExitRecvfrom,
		p.TraceSysExitRecvmsg,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
